plugins {
    id 'java-library'
    id 'maven-publish'    
    id 'com.diffplug.spotless' version '7.0.3'
    id 'com.gradleup.shadow' version '9.1.0'
}

repositories {
    // Use Maven Central for resolving dependencies.
    gradlePluginPortal()
    google()
    mavenCentral()
    maven { url "https://jitpack.io" } 
    maven { url "https://plugins.gradle.org/m2/" } 
    maven { url "https://repo.jenkins-ci.org/public/" }
    maven { url "https://repo.gradle.org/gradle/libs-releases" }
    maven { url "https://releases.usethesource.io/maven/" }
    mavenLocal()
    maven {
        url = uri("https://repository.apache.org/content/repositories/snapshots/")
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.assemble.dependsOn tasks.shadowJar
tasks.build.dependsOn tasks.shadowJar

spotless {
    java {
        target "**/*.java"		  
        googleJavaFormat()
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

shadowJar {        
    archiveFileName.set("${project.rootProject.name}.jar")       
    archiveClassifier.set("")  
 
    dependencies {
        exclude(dependency('org.codehaus.plexus:plexus-interpolation:1.28'))
        exclude(dependency('javax.inject:javax.inject:1'))
        exclude(dependency('org.apache.maven:maven-model:3.9.11'))
        exclude(dependency('org.codehaus.plexus:plexus-utils:3.6.0'))
        exclude(dependency('org.apache.maven:maven-artifact:3.9.11'))
        exclude(dependency('org.apache.maven:maven-builder-support:3.9.11'))
        exclude(dependency('org.eclipse.sisu:org.eclipse.sisu.inject:0.9.0.M4'))
        exclude(dependency('org.ow2.asm:asm:9.8'))
    }
}

dependencies {    
    implementation("org.apache.maven:maven-model-builder:3.9.11")
}

publishing {
    publications {
        shadow(MavenPublication) { publication ->            
            groupId = 'org.kodtik.ide'
            artifactId = 'maven-model-builder'
            version = '3.9.11-beta01' 
         
            from(components.shadow)
        }
    }
}